/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peopleManager.views;

import java.util.ArrayList;
/**
 *
 * @author tomif
 */
public class DetailFrame extends javax.swing.JFrame implements IDetailView{

   private String id;
    
    public DetailFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombre = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jLabelAntiguedad = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jLabelCategoria = new javax.swing.JLabel();
        jButtonCalcularSalario = new javax.swing.JButton();
        jButtonGuardarEmpleado = new javax.swing.JButton();
        jTextFieldNombreEmpleado = new javax.swing.JTextField();
        jTextFieldApellidoEmpleado = new javax.swing.JTextField();
        jTextFieldAntiguedadEmpleado = new javax.swing.JTextField();
        jLabelSalarioEmpleado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelNombre.setText("Nombre");

        jLabelApellido.setText("Apellido");

        jLabelAntiguedad.setText("Antiguedad");

        jComboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriaActionPerformed(evt);
            }
        });

        jLabelCategoria.setText("Categoria");

        jButtonCalcularSalario.setText("Calcula salario");
        jButtonCalcularSalario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCalcularSalarioMouseClicked(evt);
            }
        });

        jButtonGuardarEmpleado.setText("Guardar");
        jButtonGuardarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGuardarEmpleadoMouseClicked(evt);
            }
        });
        jButtonGuardarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelApellido)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldApellidoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(jButtonCalcularSalario))
                            .addComponent(jTextFieldNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAntiguedad)
                            .addComponent(jLabelCategoria))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonGuardarEmpleado)
                                .addGap(19, 19, 19))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldAntiguedadEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119)
                                .addComponent(jLabelSalarioEmpleado)))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombre)
                            .addComponent(jTextFieldNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelApellido)
                            .addComponent(jTextFieldApellidoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAntiguedad)
                            .addComponent(jTextFieldAntiguedadEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCategoria)
                            .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jButtonCalcularSalario)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelSalarioEmpleado)
                        .addGap(40, 40, 40)
                        .addComponent(jButtonGuardarEmpleado)))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCategoriaActionPerformed

    private void jButtonGuardarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardarEmpleadoActionPerformed

    private void jButtonCalcularSalarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCalcularSalarioMouseClicked

    }//GEN-LAST:event_jButtonCalcularSalarioMouseClicked

    private void jButtonGuardarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGuardarEmpleadoMouseClicked

    }//GEN-LAST:event_jButtonGuardarEmpleadoMouseClicked

    private void jButtonCalcularSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCalcularSalarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {}
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcularSalario;
    private javax.swing.JButton jButtonGuardarEmpleado;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JLabel jLabelAntiguedad;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelSalarioEmpleado;
    private javax.swing.JTextField jTextFieldAntiguedadEmpleado;
    private javax.swing.JTextField jTextFieldApellidoEmpleado;
    private javax.swing.JTextField jTextFieldNombreEmpleado;
    // End of variables declaration//GEN-END:variables

    @Override
    public void abrirPantalla() {setVisible(true);}

    @Override
    public void cerrarPantalla() { setVisible(false);}

    @Override
    public void mostrarListaDeCategorias(ArrayList<String> categorias) {
        for(String nombreCategoria : categorias){
            this.jComboBoxCategoria.addItem(nombreCategoria);
        }
    }

    @Override
    public void cargarAccionCalcular(Runnable accionCalcular) {
        this.jButtonCalcularSalario.addActionListener(eventoBoton -> {
            accionCalcular.run();
        });
    }
    
    @Override
    public void cargarAccionGuardar (Runnable accionGuardar) {
        this.jButtonGuardarEmpleado.addActionListener(eventoBoton -> {
            accionGuardar.run();
        });
    }
    

    @Override
    public FormularioEmpleado obtenerDatosEmpleadoFormulario(){
        String idActual = this.id;
        String categoriaSeleccionada = this.jComboBoxCategoria.getSelectedItem().toString();
        String nombreIngresado = this.jTextFieldNombreEmpleado.getText();
        String apellidoIngresado = this.jTextFieldApellidoEmpleado.getText();
        String antiguedadIngresada = this.jTextFieldAntiguedadEmpleado.getText();
        
        return new FormularioEmpleado(
                idActual, 
                nombreIngresado, 
                apellidoIngresado, 
                antiguedadIngresada,
                categoriaSeleccionada);
    }

    @Override
    public void mostrarDatosDeEmpleadoEnFormulario(FormularioEmpleado formularioEmpleado) {
        this.id = formularioEmpleado.EmpleadoId;
        this.jComboBoxCategoria.setSelectedItem(formularioEmpleado.Categoria);
        this.jTextFieldNombreEmpleado.setText(formularioEmpleado.Nombre);
        this.jTextFieldApellidoEmpleado.setText(formularioEmpleado.Apellido);
        this.jTextFieldAntiguedadEmpleado.setText(formularioEmpleado.Antiguedad);
    }

    @Override
    public void mostrarSalarioCalculado(String salarioResultante) {
        this.jLabelSalarioEmpleado.setText(salarioResultante);
    }
}
