/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peopleManager;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author tomif
 */
public class ListFrame extends javax.swing.JFrame {

    private ArrayList<Empleado> empleados = new ArrayList<Empleado>();
    
    /**
     * Creates new form ListFrame
     */
    public ListFrame() {
        initComponents();
        
        empleados.add(new Empleado("1", "Augustus", "Caesar", "15", Categoria.CTO));
        empleados.add(new Empleado("2", "Tiberius", "Claudius", "12", Categoria.MANAGER));
        empleados.add(new Empleado("3", "Caligula", "Germanicus", "8", Categoria.BACKEND));
        empleados.add(new Empleado("4", "Claudius", "Nero", "10", Categoria.DEVOPS));
        empleados.add(new Empleado("5", "Nero", "Augustus", "6", Categoria.DEVELOPER));
        empleados.add(new Empleado("6", "Vespasian", "Flavius", "14", Categoria.TECHLEAD));
        empleados.add(new Empleado("7", "Titus", "Flavius", "9", Categoria.BACKEND));
        empleados.add(new Empleado("8", "Domitian", "Augustus", "11", Categoria.MANAGER));
        empleados.add(new Empleado("9", "Trajan", "Optimus", "13", Categoria.CTO));
        empleados.add(new Empleado("10", "Hadrian", "Aelius", "10", Categoria.DEVOPS));
        
        this.rellenarTablaEmpleados();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNew = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpleados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonNew.setText("New");
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });

        jTableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Seniority", "Category", "Salary"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEmpleados);
        if (jTableEmpleados.getColumnModel().getColumnCount() > 0) {
            jTableEmpleados.getColumnModel().getColumn(0).setResizable(false);
            jTableEmpleados.getColumnModel().getColumn(1).setResizable(false);
            jTableEmpleados.getColumnModel().getColumn(2).setResizable(false);
            jTableEmpleados.getColumnModel().getColumn(3).setResizable(false);
            jTableEmpleados.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButtonNew, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNew, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNewActionPerformed

    private void jTableEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmpleadosMouseClicked
        int row = this.jTableEmpleados.getSelectedRow();
        
        DetailFrame detailFrame = new DetailFrame(empleados.get(row), this);
        
        detailFrame.setVisible(true);
        
    }//GEN-LAST:event_jTableEmpleadosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNew;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmpleados;
    // End of variables declaration//GEN-END:variables
    
    public void rellenarTablaEmpleados(){
        DefaultTableModel defaultTable = (DefaultTableModel) this.jTableEmpleados.getModel();
        defaultTable.setRowCount(empleados.size());
        
        TableModel tableModel = this.jTableEmpleados.getModel();
        
        for(int i=0; i<empleados.size(); i++){
            Empleado empleado = empleados.get(i);
            
            String id = empleado.objectId;
            String nombre = empleado.nombre;
            String apellido = empleado.apellido;
            String antiguedad = empleado.antiguedad;
            Categoria categoria = empleado.categoria;
            
            tableModel.setValueAt(id,i, 0);
            tableModel.setValueAt(nombre+  " " + apellido,i, 1);
            tableModel.setValueAt(antiguedad,i, 2);
            tableModel.setValueAt(categoria,i, 3);
            tableModel.setValueAt(empleado.calcularSalario(),i, 4);
        }
    }
    
    public void actualizarEmpleado(Empleado empleadoPorActualizar){
        String id = empleadoPorActualizar.objectId;
        for(int i=0; i<empleados.size(); i++){
            Empleado empleado = empleados.get(i);
        if(empleado.objectId.equalsIgnoreCase(id)){
            empleados.set(i, empleadoPorActualizar);
            break;
            }
        }
        this.rellenarTablaEmpleados();
    }
    
    public void insertarEmpleado(Empleado empleadoParaInsertar){
        String id = String.valueOf(empleados.size() + 1);
        empleadoParaInsertar.objectId = id;
        this.empleados.add(empleadoParaInsertar);
        rellenarTablaEmpleados();
    }
}
