/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peopleManager;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author tomif
 */
public class ListFrame extends javax.swing.JFrame {

    private ArrayList<String> empleados = new ArrayList<String>();
    
    /**
     * Creates new form ListFrame
     */
    public ListFrame() {
        initComponents();
        
        empleados.add("1,Augustus,Caesar,15,CTO");
        empleados.add("2,Tiberius,Claudius,12,Manager");
        empleados.add("3,Caligula,Germanicus,8,Backend");
        empleados.add("4,Claudius,Nero,10,DevOps");
        empleados.add("5,Nero,Augustus,6,Developer");
        empleados.add("6,Vespasian,Flavius,14,TechLead");
        empleados.add("7,Titus,Flavius,9,Backend");
        empleados.add("8,Domitian,Augustus,11,Manager");
        empleados.add("9,Trajan,Optimus,13,CTO");
        empleados.add("10,Hadrian,Aelius,10,DevOps");
        
        this.rellenarTablaEmpleados();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNew = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpleados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonNew.setText("New");
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });

        jTableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Seniority", "Category", "Salary"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEmpleados);
        if (jTableEmpleados.getColumnModel().getColumnCount() > 0) {
            jTableEmpleados.getColumnModel().getColumn(0).setResizable(false);
            jTableEmpleados.getColumnModel().getColumn(1).setResizable(false);
            jTableEmpleados.getColumnModel().getColumn(2).setResizable(false);
            jTableEmpleados.getColumnModel().getColumn(3).setResizable(false);
            jTableEmpleados.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButtonNew, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNew, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNewActionPerformed

    private void jTableEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmpleadosMouseClicked
        int row = this.jTableEmpleados.getSelectedRow();
        
        DetailFrame detailFrame = new DetailFrame(empleados.get(row), this);
        
        detailFrame.setVisible(true);
        
    }//GEN-LAST:event_jTableEmpleadosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNew;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmpleados;
    // End of variables declaration//GEN-END:variables
    
    public void rellenarTablaEmpleados(){
        DefaultTableModel defaultTable = (DefaultTableModel) this.jTableEmpleados.getModel();
        defaultTable.setRowCount(empleados.size());
        
        TableModel tableModel = this.jTableEmpleados.getModel();
        
        for(int i=0; i<empleados.size(); i++){
            String empleado = empleados.get(i);
            String[] trozo = empleado.split(",");
            String id = trozo[0];
            String nombre = trozo[1];
            String apellido = trozo[2];
            String antiguedad = trozo[3];
            String category = trozo[4];
            
            tableModel.setValueAt(id,i, 0);
            tableModel.setValueAt(nombre+  " " + apellido,i, 1);
            tableModel.setValueAt(antiguedad,i, 2);
            tableModel.setValueAt(category,i, 3);
            tableModel.setValueAt("",i, 4);
        }
    }
    
    String calcularSalario(String strAntiguedad, String strCategory) {

        int antiguedad = Integer.valueOf(strAntiguedad);

        if (antiguedad < 5) {
            return "20000";
        }
        
        String cat = strCategory.toLowerCase();

        if (antiguedad >= 5 && antiguedad < 10) {
            switch (cat) {
                case "backend":
                    return "30000";
                case "devops":
                    return "35000";
                default: /* TechLead */
                    return "45000";
            }
        }

        if (antiguedad >= 10) {
            switch (cat) {
                case "cto":
                    return "60000";
                case "devops":
                    return "55000";
                default: /* Backend */
                    return "50000";
            }
        }

        return "0";
    }
    
    public void actualizarEmpleado(String empleadoActualizado){
        String[] datosEmpleado = empleadoActualizado.split(",");
        String id = datosEmpleado[0];
        for(int i=0; i<empleados.size(); i++){
            String empleado = empleados.get(i);
            String[] strDatosEmpleado = empleado.split(",");
        if(strDatosEmpleado[0].equals(id)){
            empleados.set(i, empleadoActualizado);
            break;
            }
        }
        this.rellenarTablaEmpleados();
    }
}
